version: "3.5"

services:
    postgres:
        container_name: postgres_cda_ecf
        image: postgres:16.2
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-ecf}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ecf}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5436:5432"
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
