version: "3.5"

services:
    postgres:
        container_name: postgres_api_ecf
        image: postgres:16.2
        environment:
            POSTGRES_USER: ecf
            POSTGRES_PASSWORD: ecf
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - api_ecf
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ecf"]
            interval: 10s
            timeout: 5s
            retries: 6

    api:
        container_name: api_ecf
        image: sarahkatz/api-ecf:latest
        ports:
            - "8080:8080"
        networks:
            - api_ecf
        restart: unless-stopped
        environment:
            - spring.datasource.url=jdbc:postgresql://postgres_api_ecf:5432/ecf
        depends_on:
            postgres:
                condition: service_healthy

networks:
    api_ecf:
        driver: bridge

volumes:
    postgres:
    pgadmin:
