version: "3.5"

services:
    postgres:
        container_name: postgres_api_ecf
        image: postgres:16.2
        environment:
            POSTGRES_USER: ecf
            POSTGRES_PASSWORD: ecf
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5436:5432"
        networks:
            - api_ecf
        restart: unless-stopped

networks:
    api_ecf:
        driver: bridge

volumes:
    postgres:
    pgadmin:
