name: build and push the api image to docker hub
on:
    push:
        branches:
            - cicd

jobs:
    Build-Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PWD }}

            - name: Build
              run: docker build -t api-ecf ./api

            - name: Tag
              run: docker tag api-ecf:latest sarahkatz/api-ecf:latest

            - name: Push
              run: docker push sarahkatz/api-ecf:latest