name: build and push the api image to docker hub
on:
    push:
        branches:
            - cicd

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PWD }}

            - name: Build
              run: docker build -t "ecf-api" ./api

            - name: Push
              run: docker push "sarahkatz/ecf-api:latest"
