name: build and deploy the api image to docker hub
on:
    push:
        branches:
            - cicd

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PWD }}

            - name: Get version from pom.xml
              id: get_version
              run: |
                  VERSION=$(cat pom.xml | grep -Eo '(<version>)[^<]*(</version>)' | sed -n '2p' | sed 's/<[^>]*>//g;s/<[^>]*>//g')
                  echo "::set-output name=version::${VERSION}"

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: sarahkatz/ecf-api:${{ steps.get_version.outputs.version }}
