name: build and push the api image to docker hub
on: push

jobs:
    Sonar:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup java 17
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Launch sonar analysis
              uses: kitabisa/sonarqube-action@v1.2.0
              with:
                  host: ${{ secrets.SONARQUBE_HOST }}
                  login: ${{ secrets.SONARQUBE_TOKEN }}
